### ISSUE TITLE
Configuração inicial do Travis

### ISSUE THREAD

**Issue by maycrodrigues** [maycrodrigues/TestCI#1]
- Registrar o repositório: https://travis-ci.com
- Adicionar o `README.md` com o badge do build
- Adicionar o arquivo `.travis.yml`

```yml
language: node_js
node_js:
  - "iojs"
  - "7"
```

- Commitar
